### ISSUE TITLE
Can’t load pref

### ISSUE THREAD

**Issue by FirstJohn318** [lgariv/Selenium#5]
Installed selenium but keep getting issues in settings saying the prefbundle might be missing or broken. I forget the exact verbiage.

**Comment by lgariv** [comment]
What device, Jailbreak, and iOS version are you using?

**Comment by FirstJohn318** [comment]
iPhone 11 Pro, unc0ver 5.3.1 iOS 13.5. I restored root fs and rejailbroke and the. The first tweak I added was selenium and it had the same issue.

**Comment by lgariv** [comment]
It seems to be a problem that is specific to arm64e devices. Will solve that as soon as possible.

**Comment by FirstJohn318** [comment]
Any chance you could email me when updated so I could download it again? Instead of me checking every so often.

**Comment by lgariv** [comment]
You can follow me on Twitter and turn on notifications, I update there every time a new release / update is out.

**Comment by anazhd** [comment]
Hey I'm here to confirm the same issue. Never been working since the initial release but I forgot to report this until the recent update. Same amr64e.

**Comment by lgariv** [comment]
> Any chance you could email me when updated so I could download it again? Instead of me checking every so often.
> […](#)

> Hey I'm here to confirm the same issue. Never been working since the initial release but I forgot to report this until the recent update. Same amr64e.

Funnily enough, in the initial version it was due to another problem that was fixed in this one. Now it is caused only for arm64e and should be fixed on [v1.1.1](https://github.com/lgariv/Selenium/releases/tag/v1.1.1).

Can you confirm that?

**Comment by 2SaucesLong** [comment]
Version 1.1.1 does not fix preference issues in settings on Odyssey ios 13.5

**Comment by 2SaucesLong** [comment]
> Version 1.1.1 does not fix preference issues in settings on Odyssey ios 13.5

iPhone XS Max

**Comment by lgariv** [comment]
> > Version 1.1.1 does not fix preference issues in settings on Odyssey ios 13.5
> 
> 
> 
> iPhone XS Max

Does the tweak works except that?

**Comment by 2SaucesLong** [comment]
> > > Version 1.1.1 does not fix preference issues in settings on Odyssey ios 13.5
> > 
> > 
> > iPhone XS Max
> 
> Does the tweak works except that?

I can't tell. I'm unsure if there is a enable option in settings as I haven't been able to get the preferences file load since after 1.10. Regardless, nothing shows up to snooze notifications. I downgraded Cephei, as well I can't downgrade Selenium to try and load preferences.

**Comment by 2SaucesLong** [comment]
One more thing. It doesn't actually seem to create the preferences file. This is why I attempted to downgrade hoping it would at least load the file.

**Comment by lgariv** [comment]
> One more thing. It doesn't actually seem to create the preferences file. This is why I attempted to downgrade hoping it would at least load the file.

Does `SeleniumPrefs.bundle` exist inside `/Library/PreferenceBundles`? And is there anything inside it?

**Comment by 2SaucesLong** [comment]
> Does SeleniumPrefs.bundle exist inside /Library/PreferenceBundles? And is there anything inside it?

Yes. This could be because it was installed prior. However, they do exist. The folder consists of icons, Info.plist, Root.plist, and SeleniumPrefs.

**Comment by lgariv** [comment]
> > Does SeleniumPrefs.bundle exist inside /Library/PreferenceBundles? And is there anything inside it?
> 
> 
> 
> Yes. This could be because it was installed prior. However, they do exist. The folder consists of icons, Info.plist, Root.plist, and SeleniumPrefs.

I have just re-uploaded v1.1.1. Can you check out that build and see if it helps?

**Comment by anazhd** [comment]
Hi,

I removed the selenium pref bundle folder and Selenium it self. Reinstalled the new 1.1.1 and still the same issue. 
![C06FABBB-AA84-401A-83F6-EC88FB5EC10C](https://user-images.githubusercontent.com/2653847/91483160-d65a2280-e8d9-11ea-99f4-222aaf3420a7.png)

**Comment by 2SaucesLong** [comment]
I regret to inform you that the rerelease of v1.1.1 does not fix the issue. Continuing to test it out to see if any of the previous steps I've taken trigger this to work.

**Comment by lgariv** [comment]
Can you try now? (updated again)

**Comment by FirstJohn318** [comment]
I have yet to see version 1.1.1 out yet.

**Comment by lgariv** [comment]
> I have yet to see version 1.1.1 out yet.
> […](#)

https://github.com/lgariv/Selenium/releases/download/v1.1.1/com.miwix.selenium_1.1.1_iphoneos-arm.deb

**Comment by 2SaucesLong** [comment]
Trying now. Just got back home. Results: we have success!!! Great work.

**Comment by 2SaucesLong** [comment]
> Trying now. Just got back home. Results: we have success!!! Great work.

Settings loaded and I was greeted with the welcome splash to Selenium!

**Comment by FirstJohn318** [comment]
It’s “working” now...is this not compatible with axon reborn? The notification snoozes but doesn’t go away and then I try to open other notifications and I have to respring in order to see them

**Comment by 2SaucesLong** [comment]
> It’s “working” now...is this not compatible with axon reborn? The notification snoozes but doesn’t go away and then I try to open other notifications and I have to respring in order to see them

This update made it compatible with Axon Reborn. That doesn’t mean it will work flawless. I believe this issue has already been noted and I hope will be fixed in the future after the issues this complex tweak has presented the developer so far. I’ve stuck to using Selenium over Axon for the moment as it seems to continue to be the most stable. I’m very happy the dependencies and package uninstalling errors were fixed before anything as this caused me some trouble earlier on.

**Comment by lgariv** [comment]
> It’s “working” now...is this not compatible with axon reborn? The notification snoozes but doesn’t go away and then I try to open other notifications and I have to respring in order to see them
> […](#)

Unrelated to this issue.
Please open a new one, make it as detailed as possible (screenshots/records will help a lot).
